name: SellStick
main: com.shmkane.sellstick.SellStick
version: ${version}
api-version: 1.21
author: shmkane, TreemanKing, 1UnderTheSun, CodfishBender
depend:
  - Vault
softdepend:
  - ShopGuiPlus
  - Essentials